import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';

// Parse .env file if present (local dev). process.env takes priority so
// Netlify-injected variables always win over anything in the file.
const fromFile = {};
if (existsSync('.env')) {
  for (const line of readFileSync('.env', 'utf8').split('\n')) {
    const m = /^([A-Z_][A-Z0-9_]*)=(.*)$/.exec(line.trim());
    if (m) fromFile[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
}

const get = (k) => process.env[k] || fromFile[k] || '';

const vars = {
  apiKey:            get('FIREBASE_API_KEY'),
  authDomain:        get('FIREBASE_AUTH_DOMAIN'),
  projectId:         get('FIREBASE_PROJECT_ID'),
  storageBucket:     get('FIREBASE_STORAGE_BUCKET'),
  messagingSenderId: get('FIREBASE_MESSAGING_SENDER_ID'),
  appId:             get('FIREBASE_APP_ID'),
  adminPath:         get('ADMIN_PATH'),
};

const missing = Object.entries(vars).filter(([, v]) => !v).map(([k]) => k);
if (missing.length) {
  console.error(`gen-env: missing required environment variables: ${missing.join(', ')}`);
  process.exit(1);
}

const gen = (prod) => `// Generated by scripts/gen-env.mjs — do not edit manually.
export const environment = {
  production: ${prod},
  adminPath: ${JSON.stringify(vars.adminPath)},
  firebase: {
    apiKey:            ${JSON.stringify(vars.apiKey)},
    authDomain:        ${JSON.stringify(vars.authDomain)},
    projectId:         ${JSON.stringify(vars.projectId)},
    storageBucket:     ${JSON.stringify(vars.storageBucket)},
    messagingSenderId: ${JSON.stringify(vars.messagingSenderId)},
    appId:             ${JSON.stringify(vars.appId)},
  },
};
`;

mkdirSync('src/environments', { recursive: true });
writeFileSync('src/environments/environment.ts',      gen(false));
writeFileSync('src/environments/environment.prod.ts', gen(true));
console.log('gen-env: environment files written.');
